Add missing standard library includes for libc++ 23
libc++ 23 removed a number of transitive includes, so headers that were
previously pulled in indirectly are no longer available. Building with
LLVM 23 fails with errors such as:

  src/c_api/helpers.cpp:73:26: error: use of undeclared identifier 'malloc'
  src/include/common/task_system/task.h:65:34: error: no type named
    'exception_ptr' in namespace 'std'
  src/processor/operator/aggregate/base_aggregate.cpp:21:66: error: no
    member named 'bit_width' in namespace 'std'

Include the headers each translation unit actually uses. Two files
included the C header "math.h" while calling std::sqrt and std::log2,
which are only declared by <cmath>.